linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 8
    min-occurrences: 12
  lll:
    line-length: 140
  funlen:
    lines: 80
linters:
  enable-all: true
  fast: false
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - golint
    - ifshort
    - interfacer
    - maligned
    - nonamedreturns
    - nosnakecase
    - scopelint
    - structcheck
    - testpackage
    - varcheck
    - wsl
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "`noCopy` is unused"
    - "mnd: Magic number: 2, in"
    - "mnd: Magic number: 10, in"
    - "mnd: Magic number: 16, in"
    - "mnd: Magic number: 64, in"
    - "mnd: Magic number: 0o600, in"
    - "noCopy is missing in"
    - 'err113:'
    - "variable name 'ok' is too short"
    - "Function 'setListenConfig' has too many statements"
    - "complexity.*setListenConfig"
    - "complexity.*checkFlags"
